In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.5.1+cu124


# Introduction to Tensor

## creating torch.Tensor()

In [ ]:
#scaler
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
scalar.item()

7

In [ ]:
# vector
vector = torch.tensor([7,7,7])
vector

tensor([7, 7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([3])

In [ ]:
# MATRIX
MATRIX = torch.tensor([[7,8],
                       [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
# Tensor
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,3,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 3, 5]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

one 3*3  tensor

# Day 2

## Random tensors

why ransom tensors?

 Random tensors are important because the way many neural network learn is that they start with tensor full of random numbers and then adjust those random numbers to be better represent the data.

 `Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

In [ ]:
# Create a random tensor of size(3,4)
random_tensor  = torch.rand((3,4))
random_tensor

tensor([[0.8369, 0.7456, 0.0557, 0.2250],
        [0.5332, 0.7677, 0.9065, 0.8122],
        [0.1293, 0.3509, 0.9433, 0.2374]])

In [ ]:
# create a random tensor with similar shape to an image
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # height, width, colour channels

In [ ]:
random_image_size_tensor

tensor([[[0.3292, 0.6938, 0.8491],
         [0.9290, 0.1490, 0.5145],
         [0.9518, 0.3026, 0.2126],
         ...,
         [0.8112, 0.0264, 0.3478],
         [0.0738, 0.9429, 0.9178],
         [0.2188, 0.8845, 0.4279]],

        [[0.7906, 0.2064, 0.6527],
         [0.3402, 0.3969, 0.8017],
         [0.8919, 0.1980, 0.3271],
         ...,
         [0.8101, 0.5584, 0.6383],
         [0.4603, 0.1389, 0.4828],
         [0.7262, 0.4040, 0.5600]],

        [[0.4513, 0.1634, 0.1512],
         [0.8961, 0.4255, 0.4348],
         [0.9985, 0.1440, 0.8890],
         ...,
         [0.3330, 0.1368, 0.6745],
         [0.5405, 0.2257, 0.3823],
         [0.1949, 0.8988, 0.3238]],

        ...,

        [[0.5891, 0.6049, 0.2436],
         [0.4268, 0.3269, 0.9682],
         [0.1586, 0.2828, 0.0286],
         ...,
         [0.3557, 0.1123, 0.8209],
         [0.6755, 0.0694, 0.2239],
         [0.5493, 0.1818, 0.1355]],

        [[0.2106, 0.5021, 0.5047],
         [0.9712, 0.6275, 0.6839],
         [0.

 # Create tensors with zeros and ones

In [ ]:
### create a tensor of  all zeros
zero =torch.zeros(size=(3,5))
zero.ndim, zero.shape

(2, torch.Size([3, 5]))

In [ ]:
zero

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [ ]:
one  = torch.ones(size=(3,5))
one.ndim, one.shape

(2, torch.Size([3, 5]))

In [ ]:
t = one*zero
t

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [ ]:
# t= torch.matmul(one, zero)

In [ ]:
t

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

#### range of tensors use a arange(start, end, step)

In [ ]:
# roech.range is deprecated
torch.range(0,10)


<ipython-input-24-410628d774cb>:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0,10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [ ]:
range_vector = torch.arange(1,11,1)

In [ ]:
range_vector

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# creating tensor like
ten_zeros = torch.zeros_like(input=range_vector)

In [ ]:
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### tensor datatypes
#### default datatype is float32

**Note:** Tensor datatypes is one on the 3 big errors you'll run into with pytorch & deep Learning:
1. Tensors not right Datatypes
2. Tensors not right shape
3. Tensors not on right device

In [ ]:
float_32_tensor = torch.tensor([3.0,6.0,9.0], dtype = None)
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_32_tensor.dtype

torch.float32

## Three important arguments of tensor
1. `dtype -> specifies the datatype of tensor float32 by defalut`

2. `device -> specifies the device in which tensors computation is to be done (by defalut ='cpu') can also be cuda `

3. `requires_grad -> specifies if wwe need to track gradient of the tensor by deafault False`

In [ ]:
new_tensor = torch.tensor([1,2,3,4,5],
                          dtype=None ,# float_32 by default
                          device=None ,# cpu
                          requires_grad=False # no we dont want to track gradinets with operations
                          )

In [ ]:
new_tensor

tensor([1, 2, 3, 4, 5])

In [ ]:
float_16_tensor = new_tensor.type(torch.float16)

In [ ]:
float_16_tensor

tensor([1., 2., 3., 4., 5.], dtype=torch.float16)

# Getting informations form tensors
1. Tensor not right datatype -> to get datatype from tensor , can use `tensor.dtype`
2. Tensor not right shape -> to get shape from tensor , can use `tensor.shape`
3. Tensor not on the right Device -> to get device from tensor , can use `tensor.device`

# Manipulating Tensor Tensors (tensor operations)

Tensor Operations include:
* Addition `+`
* Subtraction `-`
* Multiplication (element-wise) `*`
* Division `\`
* Matrix multiplication (dot product) `@`

In [ ]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1,2,3])
tensor+10

tensor([11, 12, 13])

In [ ]:
# Multiply tensor by 10
tensor*10

tensor([10, 20, 30])

In [ ]:
# subtract by 10
tensor-10

tensor([-9, -8, -7])

In [ ]:
# divide by 10
tensor/10

tensor([0.1000, 0.2000, 0.3000])

In [ ]:
tensor//10

tensor([0, 0, 0])

## Try out PyTorch in-built functions
* addition -> `torch.add()` or `+`
* subtraction-> `torch.sub()` or `-`
* multiplication-> `torch.mul()` or `*`
* division -> `torch.div()` or `\`
* matrix_multiplication (dot product)-> `torch.matmul()` or `@` or `mm`

**Note:** use _ at end of these function (ex-> torch.add_()) to carry out inplace operations

A **Transpose** switches the axes or dimesions of a given tensor

use `tensor.T` to get the transpose of `tensor`

## Tensor agregaation

### Find the min, max, mean, sum ,etc (tensor aggregation)

In [ ]:
# create a tensor
x = torch.arange(0,100,10, dtype=torch.float32)
x.dtype

torch.float32

In [ ]:
#find the min
torch.min(x), x.min(), min(x)

(tensor(0.), tensor(0.), tensor(0.))

In [ ]:
# find the max
torch.max(x) , x.max(), max(x)

(tensor(90.), tensor(90.), tensor(90.))

**Note** `torch.mean()` function requires a tensor of float, complex dtype to work  

In [ ]:
# find the mean
# x=x.type(torch.float32)
torch.mean(x), x.mean()

(tensor(45.), tensor(45.))

### find the index/position of min and max in a tensor (positional min, max)

In [ ]:
x.argmin() # find the position in tensor that has the minimum value with argmim()-> returns index position of target tensor wwhere the minimum value occurs

tensor(0)

In [ ]:
x.argmax() # find the position in tensor that has the maxvalue value with argmim()-> returns index position of target tensor wwhere the minimum value occurs

tensor(9)

# Reshaping, viewing and stacking Tensors
## Reshaping , stacking, squeezing and unsqueezing tenors

* `Reshaping` - reshape an input tensor to a defined shape
*  `View` - Returns a view of an input tensor of certain shape but keep the same memory as the original tensor
* `Stacking` - combine multiple tensors on top of each other (vstack) vertical stack or side by side (hstack) horizontal stack
* `sqeeze` - removes all `1` dimensions from a tensor
* `Unsqueze` - add a `1` dimension to a target tensor
* `Permute` - Return a view if the input with dimensions permuted (swapped) in a certain way


In [ ]:
x = torch.arange(1.,10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
# reshaping
# add an extra dimension

x_reshaped = x.reshape(9,1)
x_reshaped, x_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [ ]:
x_reshaped = x.reshape(3,3)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([3, 3]))

In [ ]:
# creating the view
z= x.view(9,1)
z, z.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [ ]:
# changing the view
z[2,0]=5
z,x

(tensor([[1.],
         [2.],
         [5.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 tensor([1., 2., 5., 4., 5., 6., 7., 8., 9.]))

**note** changing the view z changes the x (because a view of a tensor shares the same memory as the original tensor)

In [ ]:
# stack tensors on top of each other
x_stacked = torch.stack([x,x,x,x], dim=0)
x_stacked, x.shape

(tensor([[1., 2., 5., 4., 5., 6., 7., 8., 9.],
         [1., 2., 5., 4., 5., 6., 7., 8., 9.],
         [1., 2., 5., 4., 5., 6., 7., 8., 9.],
         [1., 2., 5., 4., 5., 6., 7., 8., 9.]]),
 torch.Size([9]))

In [ ]:
# stack tensors on top of each other
x_stacked = torch.stack([x,x,x,x], dim=1)
x_stacked, x.shape

(tensor([[1., 1., 1., 1.],
         [2., 2., 2., 2.],
         [5., 5., 5., 5.],
         [4., 4., 4., 4.],
         [5., 5., 5., 5.],
         [6., 6., 6., 6.],
         [7., 7., 7., 7.],
         [8., 8., 8., 8.],
         [9., 9., 9., 9.]]),
 torch.Size([9]))

In [ ]:
x_stacked = torch.stack([x_reshaped, x_reshaped], dim =2)
x_reshaped , x_reshaped.shape , x_stacked , x_stacked.shape

(tensor([[1., 2., 5.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([3, 3]),
 tensor([[[1., 1.],
          [2., 2.],
          [5., 5.]],
 
         [[4., 4.],
          [5., 5.],
          [6., 6.]],
 
         [[7., 7.],
          [8., 8.],
          [9., 9.]]]),
 torch.Size([3, 3, 2]))

In [ ]:
x_stacked = torch.stack([x_reshaped, x_reshaped], dim =1)
x_reshaped , x_reshaped.shape , x_stacked , x_stacked.shape

(tensor([[1., 2., 5.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([3, 3]),
 tensor([[[1., 2., 5.],
          [1., 2., 5.]],
 
         [[4., 5., 6.],
          [4., 5., 6.]],
 
         [[7., 8., 9.],
          [7., 8., 9.]]]),
 torch.Size([3, 2, 3]))

In [ ]:
x_stacked = torch.stack([x_reshaped, x_reshaped], dim =0)
x_reshaped , x_reshaped.shape , x_stacked , x_stacked.shape

(tensor([[1., 2., 5.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([3, 3]),
 tensor([[[1., 2., 5.],
          [4., 5., 6.],
          [7., 8., 9.]],
 
         [[1., 2., 5.],
          [4., 5., 6.],
          [7., 8., 9.]]]),
 torch.Size([2, 3, 3]))

## Squeezing, Unsqueezing and Permuting Tensors

In [ ]:
# torch.sqeeze - remove all single dimensions from a target tensor
new_tensor = x.reshape(1,-1)
new_tensor, new_tensor.shape, new_tensor.squeeze(), new_tensor.squeeze().shape

(tensor([[1., 2., 5., 4., 5., 6., 7., 8., 9.]]),
 torch.Size([1, 9]),
 tensor([1., 2., 5., 4., 5., 6., 7., 8., 9.]),
 torch.Size([9]))

In [ ]:
# torch.sqeeze - remove all single dimensions from a target tensor
new_tensor = x.reshape(-1,1)
new_tensor, new_tensor.shape, new_tensor.squeeze(), new_tensor.squeeze().shape

(tensor([[1.],
         [2.],
         [5.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]),
 tensor([1., 2., 5., 4., 5., 6., 7., 8., 9.]),
 torch.Size([9]))

In [ ]:
# torch.sqeeze - remove all single dimensions from a target tensor
new_tensor = x.reshape(3,-1)
new_tensor, new_tensor.shape, new_tensor.squeeze(), new_tensor.squeeze().shape

(tensor([[1., 2., 5.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([3, 3]),
 tensor([[1., 2., 5.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([3, 3]))

In [ ]:
# torch.unsqueeze() - adds a single dimenstion to a target tensor at a specifc dim (dimension)
print(x.shape)
new_tensor = x.reshape(-1,1)
print(new_tensor)
print(new_tensor.shape)
print()
squeezed_tensor  = new_tensor.squeeze()
print(squeezed_tensor)
print(squeezed_tensor.shape)
print()
unsqueezed_tensor = squeezed_tensor.unsqueeze(dim=1)
print(unsqueezed_tensor)
print(unsqueezed_tensor.shape)


torch.Size([9])
tensor([[1.],
        [2.],
        [5.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])
torch.Size([9, 1])

tensor([1., 2., 5., 4., 5., 6., 7., 8., 9.])
torch.Size([9])

tensor([[1.],
        [2.],
        [5.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])
torch.Size([9, 1])


In [ ]:
# torch.unsqueeze() - adds a single dimenstion to a target tensor at a specifc dim (dimension)
print(x.shape)
print(x)
print()
print()
new_tensor = x.reshape(-1,1)
print(new_tensor)
print(new_tensor.shape)
print()
print()
squeezed_tensor  = new_tensor.squeeze()
print(squeezed_tensor)
print(squeezed_tensor.shape)
print()
print()
unsqueezed_tensor = squeezed_tensor.unsqueeze(dim=0)
print(unsqueezed_tensor)
print(unsqueezed_tensor.shape)

torch.Size([9])
tensor([1., 2., 5., 4., 5., 6., 7., 8., 9.])


tensor([[1.],
        [2.],
        [5.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])
torch.Size([9, 1])


tensor([1., 2., 5., 4., 5., 6., 7., 8., 9.])
torch.Size([9])


tensor([[1., 2., 5., 4., 5., 6., 7., 8., 9.]])
torch.Size([1, 9])


In [ ]:
# torch.permute - rearranges the dimensions of a target tensor in a specified order
# permute - rearrange
# very much useful  in cases of images
# some images has dimenstions as height*width*color_channels while some has color_channels*height*width
x_original = torch.rand(size=(2,2,3)) # height = 2px, widdth = 2px, color_channels = 3
x_original, x_original.shape

# [[[00c1, 00c2,00c2],
# ]]



(tensor([[[0.4583, 0.3291, 0.2947],
          [0.6001, 0.8156, 0.1094]],
 
         [[0.6538, 0.1648, 0.8843],
          [0.2765, 0.0828, 0.0797]]]),
 torch.Size([2, 2, 3]))

In [ ]:
# if we want color channels to be the first dimenstion then we will use permute
x_permuted = x_original.permute(2,0,1)
x_permuted, x_permuted.shape

(tensor([[[0.4583, 0.6001],
          [0.6538, 0.2765]],
 
         [[0.3291, 0.8156],
          [0.1648, 0.0828]],
 
         [[0.2947, 0.1094],
          [0.8843, 0.0797]]]),
 torch.Size([3, 2, 2]))

**Note** Permute is a view that is shares the same memory as the original tensor

# Idexing (selection data from tensors)
indexing with PyTorch is similar to indexing with NumPy

In [ ]:
x = torch.arange(1,10).reshape(1,3,3)
x,x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
# let's index on our new  tensor
x[0],x[0,0], x[0][0]

(tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]),
 tensor([1, 2, 3]),
 tensor([1, 2, 3]))

In [ ]:
x[0,0,0], x[0][0][0]

(tensor(1), tensor(1))

In [ ]:
# get number 8
x[0,2,1] , x[0][2][1]

(tensor(8), tensor(8))

In [ ]:
x[:,:,1]

tensor([[2, 5, 8]])

# Numpy Interaction
* data in numpy to pytorch tensor ->  `torch.from_numpy(ndarray)`
* PyTorch tensor -> Numpy -> `torch.Tensor.numpy()`

In [ ]:
import numpy as np

array =   np.arange(1.0, 8.0)
tensor = torch.from_numpy(array).type(torch.float32) # warning : when converting  from numpy -> pytorch, pytorch reflects numpy's defalut datatype of float64 unless specified otherwise
# tensor.type(torch.float32)
tensor


tensor([1., 2., 3., 4., 5., 6., 7.])

 change the value of array, what will this do to `tesnor`?

In [ ]:
tensor = torch.ones(7)
array = tensor.numpy()
array, tensor

(array([1., 1., 1., 1., 1., 1., 1.], dtype=float32),
 tensor([1., 1., 1., 1., 1., 1., 1.]))

# PyTorch Reproducibility
## Trying to take random out of random

`start with random numbers -> tensor operations -> update random numbers to try and make them better representation of data -> again -> again-> again ... `

* To redduce the randomness in neural networks and Pytorch comes the concept of a **random seed**.

* This is done to get reproducibility of ouputs while getting the benifite of randomness.
* Essentitally what the random seed does is "flavour" the randomness.

In [ ]:
# creating two random tensors
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)
print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A==random_tensor_B)

tensor([[0.5348, 0.4813, 0.2607, 0.9467],
        [0.2794, 0.4823, 0.8638, 0.2415],
        [0.0275, 0.9094, 0.7731, 0.9986]])
tensor([[0.6115, 0.6092, 0.7360, 0.7023],
        [0.0170, 0.9983, 0.6212, 0.0476],
        [0.7222, 0.0926, 0.3000, 0.5270]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
# Create to random but reproduceble tensors

# Set the random seed
RANDOM_SEED = 42

# Manually set the random seed note this works one for generating next tensor
torch.manual_seed(RANDOM_SEED)
random_tensor_c = torch.rand((3,4))


# Manually set the random seed note this works one for generating next tensor
torch.manual_seed(RANDOM_SEED)
random_tensor_d = torch.rand(3,4)

print(random_tensor_c)
print(random_tensor_d)
print(random_tensor_c==random_tensor_d)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


# Running tensors and PyRorch objects on the GPU (and making fastar computations)
Gpus = faster computations on numbers, with the help of CUDA, NVIDIA, PyTorch woking behind the scene

In [ ]:
### 1. Getting the GPU
! nvidia-smi

Mon Feb 17 14:10:50 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   34C    P8              9W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [ ]:
# check for gpu acess with pytorch
torch.cuda.is_available()

True

**run on GPU if available else use CPU**

In [ ]:
# 1 Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"

In [ ]:
#2 count the number of devices
torch.cuda.device_count()

1

### setting up device agnostic code and putting tensors ON and OFF the GPU

In [ ]:
## 3. Putting tensors (and models) on the GPU

# create a tensor (default on the CPU)

tensor = torch.tensor([1,2,3])
print(tensor, tensor.device)


# create a tensor (manully on CPU)
tensor2 = torch.tensor([4,5,6], device='cpu')
print(tensor2, tensor2.device)


# create a tensor (on GPU)
tensor3 = torch.tensor([6, 7,8], device= 'cuda')
print(tensor3, tensor3.device)

tensor([1, 2, 3]) cpu
tensor([4, 5, 6]) cpu
tensor([6, 7, 8], device='cuda:0') cuda:0


In [ ]:
# using device agnostic
tensor4 =torch.tensor([9,1,2], device=device) # the device varialble wich we set up earlier
# this will set up tesnor  into cuda if cuda(GPU) is available

print(tensor4, tensor4.device)

tensor([9, 1, 2], device='cuda:0') cuda:0


In [ ]:
#move the tensor from cpu to gpu
tensor5  = torch.tensor([2,3,4,5])
print(tensor5, tensor5.device)

#tensor.to(device) method is used to move tensor to target device

tensor5_cuda = tensor5.to(device) # device which is cuda if  gpu is available else this is  cpu
print(tensor5_cuda.device)
# print(device)

tensor([2, 3, 4, 5]) cpu
cuda:0


In [ ]:
# moving tensor back to cpu
tensor5_back_to_cpu=tensor5_cuda.cpu()
print(tensor5_cuda.device)

print(tensor5_back_to_cpu.device)

# cannot convert tensor to numpy array if the tensor is on gpu to move it to cpu then convert it to numpy array

cuda:0
cpu
